services:
  dtrack-apiserver:
    image: dependencytrack/apiserver:latest
    ports:
      - "8080:8080"  # API + UI Backend
    environment:
      ALPINE_LOG_LEVEL: info
    volumes:
      - dtrack-data:/data
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend:latest
    ports:
      - "8081:8080"  # Web UI erreichbar unter localhost:8081
    environment:
      - API_BASE_URL=http://localhost:8080  # Verbindet sich mit API-Server
    restart: unless-stopped

volumes:
  dtrack-data:
